#!/usr/bin/env python3
"""
TM.6.9A — Controlled Club Crest Downloader

Download missing club crests using one of these routes:
1) manual URL template generated by audit_missing_club_crests.py;
2) Wikimedia fallback search;
3) optional football-data.org API when FOOTBALL_DATA_TOKEN is available.

Recommended workflow:
  python scripts/assets/audit_missing_club_crests.py
  # fill reports/assets/missing_club_crests_urls_template.csv for priority clubs if desired
  python scripts/assets/download_missing_club_crests.py --from-template reports/assets/missing_club_crests_urls_template.csv --manual-only
  python scripts/assets/download_missing_club_crests.py --wikimedia-fallback --limit 50
  python scripts/assets/audit_missing_club_crests.py
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import mimetypes
import os
import re
import time
import unicodedata
from pathlib import Path
from urllib.parse import quote, urlparse

import pandas as pd
import requests

IMAGE_EXTS = {".svg", ".png", ".jpg", ".jpeg", ".webp"}

WIKIMEDIA_API = "https://commons.wikimedia.org/w/api.php"
FOOTBALL_DATA_API = "https://api.football-data.org/v4"

COMPETITION_CODES = [
    "PL", "PD", "BL1", "SA", "FL1", "DED", "PPL", "BSA", "ELC",
]


def normalize_key(value: object) -> str:
    txt = str(value or "").strip().lower()
    txt = unicodedata.normalize("NFKD", txt)
    txt = "".join(ch for ch in txt if not unicodedata.combining(ch))
    txt = re.sub(r"[^a-z0-9]+", " ", txt)
    return re.sub(r"\s+", " ", txt).strip()


def slugify(value: object) -> str:
    key = normalize_key(value)
    return re.sub(r"[^a-z0-9]+", "-", key).strip("-") or "club"


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "app").exists() or (candidate / "data").exists() or (candidate / "reports").exists():
            return candidate
    return start


def extension_from_response(url: str, content_type: str | None) -> str:
    suffix = Path(urlparse(url).path).suffix.lower()
    if suffix in IMAGE_EXTS:
        return suffix
    if content_type:
        ctype = content_type.split(";")[0].strip().lower()
        guess = mimetypes.guess_extension(ctype)
        if guess in IMAGE_EXTS:
            return guess
        if ctype == "image/svg+xml":
            return ".svg"
    return ".png"


def download_file(url: str, out_stem: str, asset_dir: Path, overwrite: bool = False, timeout: int = 25) -> tuple[bool, str, str]:
    headers = {"User-Agent": "ScoutingIQ-TFM/1.0 (educational asset audit)"}
    try:
        response = requests.get(url, headers=headers, timeout=timeout)
        response.raise_for_status()
        ext = extension_from_response(url, response.headers.get("content-type"))
        out_path = asset_dir / f"{out_stem}{ext}"
        if out_path.exists() and not overwrite:
            return True, str(out_path), "exists"
        out_path.write_bytes(response.content)
        if out_path.stat().st_size < 300:
            out_path.unlink(missing_ok=True)
            return False, "", "download_too_small"
        return True, str(out_path), "downloaded"
    except Exception as exc:
        return False, "", f"error: {exc}"


def wikimedia_search_crest(club_display: str) -> str | None:
    """Search Commons for a likely crest/logo file and return original URL."""
    queries = [
        f"{club_display} crest filetype:svg",
        f"{club_display} logo filetype:svg",
        f"{club_display} badge football club",
    ]
    session = requests.Session()
    session.headers.update({"User-Agent": "ScoutingIQ-TFM/1.0 (educational asset audit)"})
    for query in queries:
        try:
            params = {
                "action": "query",
                "generator": "search",
                "gsrsearch": query,
                "gsrnamespace": 6,
                "gsrlimit": 8,
                "prop": "imageinfo",
                "iiprop": "url|mime",
                "format": "json",
            }
            data = session.get(WIKIMEDIA_API, params=params, timeout=20).json()
            pages = data.get("query", {}).get("pages", {})
            candidates = []
            for page in pages.values():
                title = page.get("title", "")
                info = (page.get("imageinfo") or [{}])[0]
                url = info.get("url", "")
                mime = info.get("mime", "")
                score = 0
                title_key = normalize_key(title)
                club_key = normalize_key(club_display)
                if club_key and club_key in title_key:
                    score += 5
                if "svg" in mime or url.lower().endswith(".svg"):
                    score += 3
                if any(word in title_key for word in ["crest", "logo", "badge"]):
                    score += 2
                if any(bad in title_key for bad in ["kit", "shirt", "jersey", "flag"]):
                    score -= 5
                if url:
                    candidates.append((score, title, url))
            candidates.sort(reverse=True, key=lambda x: x[0])
            if candidates and candidates[0][0] >= 4:
                return candidates[0][2]
        except Exception:
            continue
    return None


def football_data_team_crests(token: str, codes: list[str]) -> dict[str, str]:
    """Return normalized team name -> crest URL from football-data.org."""
    out: dict[str, str] = {}
    headers = {"X-Auth-Token": token, "User-Agent": "ScoutingIQ-TFM/1.0"}
    for code in codes:
        try:
            url = f"{FOOTBALL_DATA_API}/competitions/{quote(code)}/teams"
            response = requests.get(url, headers=headers, timeout=25)
            if response.status_code == 429:
                time.sleep(65)
                response = requests.get(url, headers=headers, timeout=25)
            response.raise_for_status()
            for team in response.json().get("teams", []):
                crest = team.get("crest")
                if not crest:
                    continue
                names = [team.get("name"), team.get("shortName"), team.get("tla")]
                for name in names:
                    key = normalize_key(name)
                    if key:
                        out[key] = crest
        except Exception as exc:
            print(f"WARN: football-data {code}: {exc}")
    return out


def load_template(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    df = pd.read_csv(path)
    required = {"club_display", "slug_expected"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Template missing columns: {sorted(missing)}")
    if "crest_url" not in df.columns:
        df["crest_url"] = ""
    if "preferred_filename" not in df.columns:
        df["preferred_filename"] = df["slug_expected"].astype(str) + ".svg"
    return df


def append_manifest(manifest_path: Path, row: dict[str, str]) -> None:
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    exists = manifest_path.exists()
    fieldnames = ["club_display", "asset_file", "source", "source_url", "status", "last_checked"]
    with manifest_path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not exists:
            writer.writeheader()
        writer.writerow({k: row.get(k, "") for k in fieldnames})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--asset-dir", default="app/assets/clubs")
    parser.add_argument("--from-template", default="reports/assets/missing_club_crests_urls_template.csv")
    parser.add_argument("--manifest", default="app/assets/clubs/club_crests_manifest.csv")
    parser.add_argument("--manual-only", action="store_true", help="Only use crest_url values from the template")
    parser.add_argument("--wikimedia-fallback", action="store_true", help="Search Wikimedia Commons when crest_url is empty")
    parser.add_argument("--football-data", action="store_true", help="Use football-data.org when FOOTBALL_DATA_TOKEN is available")
    parser.add_argument("--limit", type=int, default=0, help="Max rows to process; 0 = all")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    root = find_project_root(Path(args.root).resolve())
    asset_dir = root / args.asset_dir
    asset_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = root / args.manifest

    template_path = root / args.from_template
    df = load_template(template_path)
    if args.limit and args.limit > 0:
        df = df.head(args.limit)

    fd_lookup: dict[str, str] = {}
    token = os.getenv("FOOTBALL_DATA_TOKEN", "").strip()
    if args.football_data and token:
        fd_lookup = football_data_team_crests(token, COMPETITION_CODES)
    elif args.football_data and not token:
        print("WARN: --football-data requested but FOOTBALL_DATA_TOKEN is not set.")

    results = []
    for _, row in df.iterrows():
        club = str(row.get("club_display", "")).strip()
        slug = str(row.get("slug_expected", "")).strip() or slugify(club)
        preferred = str(row.get("preferred_filename", "")).strip()
        out_stem = Path(preferred).stem if preferred else slug
        crest_url = str(row.get("crest_url", "") or "").strip()
        source = str(row.get("source", "manual") or "manual").strip()

        if not crest_url and fd_lookup:
            crest_url = fd_lookup.get(normalize_key(club), "")
            source = "football-data.org" if crest_url else source
        if not crest_url and args.wikimedia_fallback and not args.manual_only:
            crest_url = wikimedia_search_crest(club) or ""
            source = "wikimedia" if crest_url else source

        if not crest_url:
            status = "no_url"
            asset_file = ""
            ok = False
        elif args.dry_run:
            status = "dry_run"
            asset_file = str(asset_dir / f"{out_stem}<ext>")
            ok = True
        else:
            ok, asset_file, status = download_file(crest_url, out_stem, asset_dir, overwrite=args.overwrite)

        result = {
            "club_display": club,
            "asset_file": str(Path(asset_file).as_posix()) if asset_file else "",
            "source": source,
            "source_url": crest_url,
            "status": status,
            "last_checked": dt.date.today().isoformat(),
        }
        append_manifest(manifest_path, result)
        results.append(result)
        print(f"{club:35} {status:18} {Path(asset_file).name if asset_file else ''}")
        time.sleep(0.25)

    out_path = root / "reports" / "assets" / "club_crest_download_results.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(results).to_csv(out_path, index=False)
    print(f"\nSaved: {out_path}")
    print(f"Manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
